<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GraphEngine\GraphEngine.csproj" />
    <ProjectReference Include="..\JobPostings\JobPostings.csproj" />
    <ProjectReference Include="..\CvExtraction\CvExtraction.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
